### Crear playlist (multipart/form-data)
POST http://localhost:8080/api/playlists/crear
Authorization: Bearer {{tokenUsuario}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombrePlaylist"

{{nombrePlaylist}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="esPublica"

{{esPublica}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fotoPortada"; filename="portada.png"
Content-Type: image/png

< {{rutaDeLaPortada}}
------WebKitFormBoundary7MA4YWxkTrZu0gW

# Respuesta esperada: 201 Created
