spring.application.name                     = KeySound-BackEnd

server.port                                 = 8080

# Database Configuration
spring.datasource.url                       = ${DB_URL}
spring.datasource.username                  = ${DB_ROOT_USER}
spring.datasource.password                  = ${DB_ROOT_PASSWORD}
spring.jpa.hibernate.ddl-auto               = validate
spring.jpa.show-sql                         = true
spring.jpa.properties.hibernate.format_sql  = true

# Firebase Configuration
# Tamanio maximo permitido para un solo archivo y para una solicitud completa (puede incluir varios archivos)
spring.servlet.multipart.max-file-size      = 10MB
spring.servlet.multipart.max-request-size   = 60MB