### Prueba de subida de lanzamiento (sencillo)
POST http://localhost:8080/api/artistas/subir-sencillo
Authorization: Bearer (tokenArtista)
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nombreSencillo"

(nombre del sencillo)
--WebAppBoundary
Content-Disposition: form-data; name="portada"; filename="2Tonos_Portada.jpg"
Content-Type: image/jpeg

< (ruta a tu archivo de imagen)
--WebAppBoundary
Content-Disposition: form-data; name="cancion"; filename="2Tonos.mp3"
Content-Type: audio/mpeg

< (ruta a tu archivo de audio)
--WebAppBoundary