### Crear playlist (sin foto de portada)
POST http://localhost:8080/api/usuarios/crear-playlist
Authorization: Bearer (tokenUsuario)
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="nombrePlaylist"

{nombre de la playlist}
--boundary
Content-Disposition: form-data; name="esPublica"

{true o false}
--boundary--
